# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 16:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='NCCTermParms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('primaryNCCnumber', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Primary NCC number')),
                ('alternateNCCnumber', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Alternate NCC number')),
                ('CADId', models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True, verbose_name='CAD ID')),
                ('CPEId', models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True, verbose_name='CPE ID')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
            options={
                'verbose_name': 'NCC/terminal access parameters',
                'verbose_name_plural': 'NCC/terminal access parameters',
            },
        ),
        migrations.AlterUniqueTogether(
            name='ncctermparms',
            unique_together=set([('name', 'tenant')]),
        ),
    ]
